chanzuckerberg/czid-graphql-federation-server

.meshrc.yaml

[CZID-8322]
Pass CSRF token to CZ ID Rails webapp graphQL endpoint when it is available as a header.  This increases protection against CSRF attacks when querying the CZ ID Rails webapp graphQL API
* Related CZ ID PR: chanzuckerberg/czid-web-private/pull/4049
* In local dev, this was safe to deploy even if the React Relay client was not sending CSRF tokens in the header.  I will verify on sandbox as well, but this should be safe to deploy independently of CZ ID changes.
* deployed this branch to `sandbox` env, and `main` branch of `czid-web` to `sandbox` env, and things still worked (so basically this PR is ok even if there is no X-CSRF header in the request).
[CZID-8322]: https://czi-tech.atlassian.net/browse/CZID-8322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

feat: Pass CSRF token when querying CZID Rails graphql

---

sources/czid-schema.graphql

[CZID-8652]
Change graphql scheme to match changes in this [PR](https://github.com/chanzuckerberg/czid-web-private/pull/4052/)
This is a non-breaking change. The federated `sampleReadsStats` query is not currently being used in the web-app.
Note that this change must be merged before the associated PR on the web-app side can be merged.
Tested locally
[CZID-8652]: https://czi-tech.atlassian.net/browse/CZID-8652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: swap sampleId type to ID to support QualityControlQuery

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-sandbox.yml
.github/workflows/deploy-staging.yml
.happy/version.lock

[CZID-8804]
Implement prod deployment by promoting images from staging to prod.  Locks our deploy action to use the version containing chanzuckerberg/github-actions/pull/228, which enables a new argument needed for this feature.
[CZID-8804]: https://czi-tech.atlassian.net/browse/CZID-8804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* Set `IMAGE_SOURCE_ROLE_ARN` as Github secret in production environment
* `IMAGE_SOURCE_ENV` and `IMAGE_SOURCE_STACK` were previously set.

feat(ci): promote images from staging when deploying to prod

---

sources/czid-schema.graphql

Reverts chanzuckerberg/czid-graphql-federation-server#20
Re-releasing #16 as a breaking change.  As mentioned in #16, this will not break anything in CZ ID, because the graphQL mesh federated query is not currently in use, but changing types in a graphQL schema should generally be considered a breaking change, and we do want this to be explicitly included in a release.

feat!: swap sampleId type to ID to support QualityControlQuery

---

.meshrc.yaml
package-lock.json
package.json

[CZID-8322]
Add CSRF protection to graphQL mesh using `@graphql-yoga/plugin-csrf-prevention`: https://the-guild.dev/graphql/mesh/docs/plugins/csrf. 
Remove CSRF token being passed as header, as this check is now disabled.
* We need to wait until this PR is merged to that appropriate headers are being sent by the React app.
* deployed in chanzuckerberg/czid-web-private/pull/4114
1. Containers need to be rebuilt:
```
docker compose down
docker compose build
docker compose up
```
2.  CSRF header need to be added to GraphiQL if you wish to use the playground:
```
{
"x-graphql-yoga-csrf": "csrf",
}
````
Test that there are no regressions in functionality that uses Rails graphQL schema.  This includes the following:
* Pathogen list
* Quality control page
* User creation
[CZID-8322]: …

feat: Add CSRF prevention plugin

---

.meshrc.yaml
docker-compose.yml

[CZID-8925]
Restrict the CORS Origins for graphQL mesh to address Armor Code security alert.  See JIRA ticket for details.
* Must add new `ALLOWED_CORS_ORIGINS` env var for each environment
* Manually test that graphQL queries in playground and webapp work
[CZID-8925]: https://czi-tech.atlassian.net/browse/CZID-8925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: restrict CORS origin for graphQL mesh

---

json-schemas/sampleMetadata.json

JIRA Ticket - no ticket
Changing the `ercc_comparison.expected` type from integer to float will all the correct value to come through the mesh server rather than null. This is to unblock [CZID-8606](https://czi-tech.atlassian.net/browse/CZID-8606)
The following query should **not** return `null` as an `expected` value.
```
query MyQuery {
SampleMetadata(sampleId: "26940") {
additional_info {
ercc_comparison {
actual
expected
name
}
}
}
}
```
[CZID-8606]: https://czi-tech.atlassian.net/browse/CZID-8606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change ercc_comparison type from integer to float

---

json-schemas/locationV2.json
json-schemas/sampleMetadata.json
json-schemas/updateMetadata.json
resolvers.ts
sample-responses/locationV2.json

[CZID-9028](https://czi-tech.atlassian.net/browse/CZID-9028)
The `location_validated_value` needed to be added to the metadata items but also it needed to account for the fact that sometimes it will return a string and sometimes a location object. This required using a Union type and adjusting the resolver to tell GraphQL what the returned type was using the `__typename` field.
We also had to change the UpdateMetadata query to accept Location Objects as well as strings as their value.
Try to test on a Sample with a string location value and an object location value:
```query MyQuery {
SampleMetadata(sampleId: "24142") {
metadata {
raw_value
location_validated_value {
... on query_SampleMetadata_metadata_items_location_validated_value_oneOf_0 {
name
}
... on …
```

fix: adding multiple location types and Update metadata values

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml

[CZID-9222]
These are the first steps in updating the release cadence for this service.
* Turn off automatic staging deploys (on PR merge)
* Test github action script to get the latest or a specified release tag
Eventually, if we want to move back to a on-demand or continuous release cadence, we'll likely need to undo most of this PR.  To make sure this doesn't get lost, the original commit to stop automatic staging deploys is here: https://github.com/chanzuckerberg/czid-graphql-federation-server/pull/67/commits/0d22c3cb0d5f59503006b4a713d5b40bfc6ab242
This is mostly a reminder, but the `deploy-happy-stack` checks out the repo on its own.  This is an important distinction because whatever `ref` that is checked out by a github action is not used by the `deploy-happy-stack` action. …

feat(ci): Align release process to CZ ID manual release cadence

---

.github/workflows/deploy-prod.yml

[CZID-9222]
Parsing the release response in bash leads to issues with quotes, so just get the release tag name in JS.

fix: get release tag in github script step

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml
README.md

[CZID-9222]
- Add manual workflow option for staging deploy, and use composite action to get release tag for staging
- Re-enable prod deploy
- Specify github branch (tag) for both staging and prod deploy
- Update docs
Will be running deploys using the updated scripts in line with the CZ ID release cadence.

feat: allow manual staging deploy, re-enable prod deploy

---

.meshrc.yaml
example-queries/consensus-genomes-query.graphql
example-queries/samples-query.graphql
example-queries/sequencing-reads-query.graphql
example-queries/workflow-runs-query-empty.graphql
example-queries/workflow-runs-query-id-list.graphql
example-queries/workflow-runs-query-order-by.graphql
json-schemas/consensusGenomesRequest.json
json-schemas/consensusGenomesResponse.json
json-schemas/samplesRequest.json
json-schemas/samplesResponse.json
json-schemas/sequencingReadsRequest.json
json-schemas/sequencingReadsResponse.json
json-schemas/workflowRunsRequest.json
resolvers.ts
tests/BulkDownloadCGOverview.test.ts
tests/ConsensusGenomesQuery.test.ts
tests/CreateBulkDownload.test.ts
tests/SamplesQuery.test.ts
tests/SequencingReadsQuery.test.ts
tests/WorkflowRunsQuery.test.ts
tests/ZipLinkQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap
tests/utils/ExampleQueryFiles.ts

[CZID-9351]
[CZID-9353]
These 2 endpoints will be used for retrieving the actual (paginated) sample rows. The will used the list of perfectly filtered IDs as input in NextGen.
`sequencingReads` can fully substitute for querying `samples` since it's a 1:1 relationship (can handle sorting on nested `Sample`s). It will also be the query that handles sorting by metadata fields, which (while Rails contains all metadata) will require the Federation layer to query a different Rails endpoint for the `Sample`s sorted by metadata.
`consensusGenomes` is necessary for sorting on `ConsensusGenome` fields. The query itself is not sufficient due to `Sample`s that don't have `ConsensusGenome`s, so the FE will have to stitch the result together with those `Sample`s.
Also updated the `samples` endpoint:
- …

feat: Federate sequencingReads and consensusGenomes

---

example-queries/consensus-genomes-query.graphql
example-queries/sequencing-reads-query.graphql
json-schemas/consensusGenomesRequest.json
json-schemas/consensusGenomesResponse.json
json-schemas/sequencingReadsRequest.json
json-schemas/sequencingReadsResponse.json
json-schemas/workflowRunsRequest.json
resolvers.ts
sources/entities-schema.graphql
tests/SequencingReadsQuery.test.ts
tests/WorkflowRunsQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

[CZID-9400]
Adds limit/offset to paginated fields.
Adds a temporary `uploadError` field, which should actually be errors from R1 and R2 but that will be done later.
Notice I had to delete `sequencingReads` and `consensusGenomes` from entities-schema.graphql because their types conflict with the custom types defined in our JSON files. We're unable to use exactly the NextGen return types while things like projects and users haven't been migrated, those have to be custom fields in the schema that don't exist in NextGen. I tried reordering the sources in .meshrc.yml to see if I could get the custom schemas to override that way, but it didn't work.
Also added fallbacks for required GQL fields because the corresponding fields in Rails don't have great guarantees that they'll actually exist (and …

feat: Update paginated endpoints with limit/offset

---

.meshrc.yaml
example-queries/samples-query.graphql
example-queries/sequencing-reads-query.graphql
example-queries/workflows-aggregate-query.graphql
resolvers.ts
tests/SamplesQuery.test.ts
tests/SequencingReadsQuery.test.ts
tests/WorkflowRunsAggregateQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

Adds `fed` prefix to:
- `samples`
- `sequencingReads`
- `workflowRunsAggregate`
None of these are used in prod right now.
Suzette is taking care of `consensusGenomes`. `workflowRuns` is in prod but does not conflict in response type, so hopefully it will just work once the NextGen schema and types are available on the FE.
This also adds a small fix to the `location` field (that seems to be the only metadata field that can either be an `object` or a `string`...).

feat: Add fed prefix to a few fields

---

.meshrc.yaml
json-schemas/fedWorkflowRunsRequest.json
json-schemas/fedWorkflowRunsResponse.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

If I reuse the schema files, Mesh will generate the same input and response type names for the 2 queries, which might cause the requests to break during the transition where we delete the old federated `workflowRuns` field (which would cause the type to switch from `workflowRunsInput` to `fedWorkflowRunsInput`).
Unused endpoint.

chore: Duplicate the JSON schema files for workflowRuns so that it generates different input types

---

json-schemas/createBulkDownloadCSV.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

none
Change workflowRunIdsStrings type and remove required for workflowRunIds so the frontend can choose to send only workflowRunIdsStrings.

fix: createBulkDownload Change workflowRunIdsStrings type and remove required for workflowRunIds

---

Makefile
sources/nextgen-entities-schema.graphql
sources/nextgen-workflows-schema.graphql
tests/__snapshots__/UnifiedSchema.test.ts.snap

N/A
Update the nextGen schemas in the source files to pick up the following updates:
* Adding `uploadError`, `createdAt`, and `updatedAt` to `Files` in Entities
* Adding `limit` and `offset` as inputs for both Entities and Workflows
We should try to automate this in the long-term. In the short-term, I will add documentation on how to do this.
N/A

chore: Update nextGen schemas in sources

---

resolvers.ts
tests/WorkflowRunsQuery.test.ts
utils/queryFormatUtils.ts

Entity inputs are underscore now.
FE doesn't read this field directly (it assumes that the only entity input is for the sequencing read, because we query `entityInputs` with a filter).

fix: Change to underscore entity input format

---

json-schemas/sampleForReportResponse.json
resolvers.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

no ticket
Make default pipeline id into a string so that it can be matched on the front end. 
This bug was keeping the header buttons from showing on Sample Report.
Load Sample Report with next gen flag off and see no buttons on pipeline tabs.

fix: Sample View header & pipeline version

---

resolvers.ts
tests/SequencingReadsQuery.test.ts

Ideally this would've never happened, but currently we have `WorkflowRun`s that point to non-existent `SequencingRead`s in staging. We never want to send no `sampleIds` to Rails, otherwise it will join every `Sample` ever.
Staging should stop lagging.

fix: Don't call Rails for the join if there were no sequencing reads returned by NextGen

---

resolvers.ts

none
For non-wgs workflow runs and non-migrated workflow runs, this should just return the data from rails rather than crashing.  This is expected for workflowRuns/pipelineRuns that are not WGS and for data that hasn't migrated yet.

fix: return rails data when no nextgen id available

---

example-queries/workflow-runs-query-order-by-array.graphql
resolvers.ts
tests/WorkflowRunsQuery.test.ts
tsconfig.json
utils/enrichToken.ts

FE is now using `orderByArray` so that's what we should be sending to NextGen.
In prod today, we technically show the name of the workflow runner, and if that doesn't exist we fall back to the name of the sample uploader. Showing that in NextGen would require us to add a join to Rails in `fedWorkflowRuns`, which may not be worth doing right now given the effort and additional latency that would incur. I've created a Jira to track it for now: https://czi-tech.atlassian.net/browse/CZID-9467
Also add a tsconfig.json to Fed because apparently we didn't have one (and as a result of this, now VSCode is properly saying some variables are possibly undefined, so fix those)!
A name should appear in the "Sample" column in the CG table in NextGen.
CG runs should be default sorted by time in NextGen.

fix: Add sample uploader name to joined data from Rails + Use new array orderBy argument for NextGen

---

example-queries/workflows-aggregate-query.graphql
json-schemas/workflowRunsAggregateRequest.json
json-schemas/workflowRunsAggregateResponse.json
resolvers.ts
sample-requests/workflowRunsAggregate.json
sample-responses/workflowRunsAggregate.json
tests/WorkflowRunsAggregateQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap
utils/aggregateUtils.ts

[CZID-9419]
Query CG runs from next gen and make the response look next-gen-y
- writing endpoint so that we can either make one aggregate query per workflow (e.g. CG, AMR, mNGS each hit the aggregate endpoint) or we just do one big query by joining all the workflow run ids together. This way we can change the frontend without changing the federation layer.
- it's sort of convoluted to process the rails data into the `groupBy` format and then unprocess it into a usable format on the frontend but it fits into how the response will ultimately look on the FE
Hit endpoint from GraphiQL and from frontend code successfully. Ran NextGen query in staging and confirmed it returned correct results.
[CZID-9306]: https://czi-tech.atlassian.net/browse/CZID-9306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

feat: query aggregates from NextGen and reformat response

---

example-queries/sequencing-reads-query-fe.graphql
example-queries/sequencing-reads-query-id-fe.graphql
example-queries/workflow-runs-query-fe.graphql
resolvers.ts
tests/SequencingReadsQuery.test.ts
tests/WorkflowRunsQuery.test.ts
tests/utils/StringUtils.ts
utils/queryFormatUtils.ts

I was using the wrong IDs to filter `ConsensusGenome`s, therefore wasn't getting any back.
Also add support for query that only fetches `id` (will be used for filters).
Also fix test util assert function that wasn't properly handling single whitespace characters.
Should be able to see `ConsensusGenome` fields in samples table in NextGen.

fix: Use workflowRun IDs in inner consensusGenomes where, not sequencingRead IDs

---

tests/WorkflowRunsQuery.test.ts
utils/queryFormatUtils.ts

Apparently `inputEntityId` can be `null`.
Samples view for NextGen should now display correct staging migrated data.

fix: Filter out WorkflowRuns with null sequencing_read inputEntityIds

---

json-schemas/workflowRunsRequest.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

We can only have `WorkflowRun`s with `"sequencing_read"` `entityType`s and non-null `inputEntityId`s.
Field not used yet.

fix: Add schema for fedWorkflowRuns for filtering out WorkflowRuns that don't have the correct input entity

---

resolvers.ts

[CZID-9382](https://czi-tech.atlassian.net/browse/CZID-9382)
The return path for Ziplink was not correct. 
Should be able to download a link from a Consensus Genome with some information on it on Staging with the Read From Next Gen Flag on. 
[CZID-9382]: https://czi-tech.atlassian.net/browse/CZID-9382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Ziplink return from NextGen

---

resolvers.ts

none
We added an optional workflowRunIdsStrings param, but it wasn't being used.

fix: convert and use workflowRunIdsStrings if passed in

---

resolvers.ts

The error was unfortunately not being thrown from our code, but a third party library Mesh depends on to validate responses (and the error had nothing to do with the actual issue either). The actual issue was that when the Rails sample doesn't exist, we weren't setting some required fields.
Removes the logs, which confirmed the error was not being thrown from our code.
NextGen samples table should start paginating.

fix: Fix required fields in sequencingReads not being set when no Rails sample found

---

resolvers.ts

Fixes the `where` clause in the next gen workflow runs aggregate query
Don't have any workflows data locally but didn't see errors in the logs of the workflows service when I ran the query from the frontend.

fix: Construct nextgen aggregates query appropriately

---

json-schemas/sequencingReadsRequest.json
resolvers.ts
tests/SequencingReadsQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap
tests/utils/MeshInstance.ts
utils/queryFormatUtils.ts

This sends taxon filters to NextGen and sample metadata based filters to Rails.
The calls are synchronous so I can filter down the Rails call to only the samples we care about (and not do full table joins).
The NextGen query is modified (FE only needs `id`) to include `sample { railsSampleId }` so we can do the join with Rails.
Functionality not used yet.

feat: Add support for filtering IDs of SequencingReads

---

resolvers.ts

no ticket
Make it possible for Taxon Name to be read on Sample report
Should be able to view Taxon name on CG Sample report with this sister PR: https://github.com/chanzuckerberg/czid-web-private/pull/4396

fix: fedConsensusGenomes: Make name available in rails

---

json-schemas/consensusGenomesRequest.json
resolvers.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

Adds `sampleIds` to todoRemove so we can filter consensusGenomes by sampleIds 
Needed for API testing

chore: Add sampleIds & workflowRunIds on fedConsensusGenome for API testing

---

tests/WorkflowRunsQuery.test.ts
utils/queryFormatUtils.ts

none
Updating syntax
Works in sandbox
When on the CG SamplesView page, select some samples and open the BulkDownloadModal.  The modal should open without giving an error.

fix: BulkDownloadModal Validation - Reformat query

---

resolvers.ts

none
Fixes csv download through the BulkDownloadModal when the NextGen flag is off
Fixes this:

fix: Use workflowRunIdsNumbers when available

---

json-schemas/consensusGenomesResponse.json
resolvers.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

[CZID-9499]
The Download Custom Reference button was not working with NextGen flags on because the call to get the download url was not federated.  This adds the field to fedConsensusGenome
I confirmed on Sandbox that this works when connected to rails.  It needs further testing for the connection to NextGen.
[CZID-9499]: https://czi-tech.atlassian.net/browse/CZID-9499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CZID-9499 Add referenceGenome to fedConsensusGenome

---

package.json
tests/utils/MockContext.ts
utils/httpUtils.test.ts
utils/httpUtils.ts

N/A
Support optional passing of security token to `get`/`fetchFromNextGen`.  This allows resolvers or other callers to retrieve and cache a security token across multiple calls to avoid fetching multiple security tokens in rapid succession.
N/A
- Unit tests added
- Deployed to sandbox and checked that discovery view and a project view loaded without error

feat: Allow security token to be passed for nextGen calls

---

json-schemas/consensusGenomesRequest.json
json-schemas/consensusGenomesResponse.json
resolvers.ts
tests/FedConsensusGenomesQuery.test.ts
tests/SequencingReadsQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap
utils/queryFormatUtils.ts

Note that this is getting rid of a lot of the previously written logic in this resolver for discovery view 🎉. We no longer need all that now that this query will not be used for actual paginated data, but only for generating the listed of filtered + sorted IDs.
Also fixes the `sequencingReads` query to NextGen not sending `orderBy`.

feat: Add sorting by consensusGenomes field functionality in Fed

---

example-queries/workflow-runs-aggregate-total-count-query.graphql
example-queries/workflows-aggregate-query.graphql
json-schemas/fedWorkflowRunsAggregateTotalCountRequest.json
json-schemas/workflowRunsAggregateRequest.json
sample-requests/fedWorkflowRunsAggregateTotalCount.json
sample-requests/workflowRunsAggregate.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

Adds `deprecatedById` field to aggregate queries so we can filter out deprecated runs
Unit tests updated

fix: allow for deprecatedById field in aggregate queries

---

resolver-functions/fedBulkDownloads.ts
resolver-functions/fedBulkDownloads/fedBulkDownloads.test.ts
resolver-functions/fedBulkDownloads/fedBulkDownloads.ts
resolvers.ts

no ticket 
Consume new merged bulk download rails endpoint that has all the data in one call so that we don't have to make multliple calls to the details endpoint. 
Final fix for undefined bug. 
Dependant on this PR https://github.com/chanzuckerberg/czid-web-private/pull/4478
- Should be able to load `/bulk_downloads` without undefined errors

fix: Use new Bulk Downloads Endpoint

---

json-schemas/sequencingReadsRequest.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

Allows us to filter out nested `ConsensusGenome`s that don't correspond to the filtered `WorkflowRun`s.
Not used yet.

feat: Add producingRunId to request schema of sequencingReads

---

json-schemas/sequencingReadsResponse.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

none
makes the taxon level available
I'm not sure why the snapshot update changed some dates from DateTime to ISO8601DateTime here, but it seems ok?
updated snapshot

fix: Add taxon level to fedSequencingReads

---

sources/nextgen-entities-schema.graphql
tests/__snapshots__/UnifiedSchema.test.ts.snap

[CZID-9505]
Update the nextGen entity schema in the source file to pick up the following updates:
* Allow `collectionId` on entities to be null
See the platformics PR for more details: https://github.com/chanzuckerberg/czid-platformics/pull/279
N/A
N/A
[CZID-9505]: https://czi-tech.atlassian.net/browse/CZID-9505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update collectionId in entity schema to be nullable

---

resolvers.ts
tests/SequencingReadsQuery.test.ts

`collection_location_v2` is the only metadata field that is sometimes an object.
This was actually handled in the old `consensusGenomes` endpoint, but I forgot to also add the fix to `sequencingReads`.

fix: Handle object type in collection_location_v2

---

resolvers.ts

This wasn't causing issues in the frontend, but it was returning an error along with the fed response for the sample view consensus genome query when it was a WGS sample without taxon id or accession (which happens if you select "unknown") in the upload.

fix: make taxon info optional in response

---

sources/nextgen-workflows-schema.graphql
tests/__snapshots__/UnifiedSchema.test.ts.snap

[CZID-9505]
Update the nextGen workflow schema in the source file to pick up the following updates:
* Allow `collectionId` on workflowRuns to be null
See the platformics PR for more details: https://github.com/chanzuckerberg/czid-platformics/pull/282
N/A
N/A
[CZID-9505]: https://czi-tech.atlassian.net/browse/CZID-9505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update collectionId in workflow schema to be nullable

---

resolver-functions/SampleForReport.ts
tests/SampleForReportQuery.test.ts

[CZID-9522]
Follow up to #310 to fix workflows query syntax and only fire taxon/accession query conditionally
[CZID-9522]: https://czi-tech.atlassian.net/browse/CZID-9522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix workflows query syntax and conditionally fire taxon/accession queries in sample report

---

package-lock.json
package.json
utils/httpUtils.test.ts
utils/httpUtils.ts

The new version of Mesh adds the implementation for making `Error`s get logged.
For whatever reason, Node.js's `json()` function doesn't return an `Error` with a stacktrace, so we have to manually catch that and throw a real `Error` if we want a stacktrace from it.
I also switched the `Promise.reject()`s to just `throw`s since it's a bit more concise.

feat: Upgrade Mesh again to enable error logging

---

.meshrc.yaml
json-schemas/createBulkDownloadResponse.json
resolver-functions/CreateBulkDownload/CreateBulkDownload.test.ts
resolver-functions/CreateBulkDownload/CreateBulkDownload.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap
utils/httpUtils.ts

Just return the ID (not currently using any of the fields anyways) if successful.
I changed the response name so it doesn't conflict with the NextGen type.

fix: Make response schema for CreateBulkDownload consistent between flag on/off

---

sources/nextgen-entities-schema.graphql
sources/nextgen-workflows-schema.graphql
tests/__snapshots__/UnifiedSchema.test.ts.snap

N/A
Updates the nextgen schemas:
* Add error label to workflwRun
* On taxa, allow users to query for taxClassId, taxFamilyId, etc.
* On workflowRuns, allow users to query for deprecatedById
See platformics PRs for more details:
* https://github.com/chanzuckerberg/czid-platformics/pull/299
* https://github.com/chanzuckerberg/czid-platformics/pull/300
N/A
N/A

fix: Update schema

---

example-queries/sample-for-report-query.graphql
json-schemas/sampleForReportResponse.json
resolver-functions/SampleForReport.ts
sample-responses/sampleForReport.json
tests/SampleForReportQuery.test.ts
tests/__snapshots__/UnifiedSchema.test.ts.snap

What was previously returned by NextGen as `errorMessage` should've actually been the label. Now there is an `errorLabel` field and `errorMessage` contains the actual sentence explaining the error. Pass these down to the sample report in an object to what Rails returns (and what the FE expects) today.

fix: Update NextGen schema with new errorLabel field and pass it through SampleForReport

---

json-schemas/workflowRunsResponse.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

This will be used by the FE to alter `status` since NextGen does not have the capability to do so.

feat: Expose errorLabel in fedWorkflowRuns

---

.github/workflows/deploy-prod.yml

* Adds the nextgen entities and workflows URL to the production happy environment
* @valenzuelaomar

feat: add nextgen entities and workflows url

---

resolver-functions/fedSequencingReads/fedSequencingReads.ts
tests/ParamsUtils.test.ts
utils/paramsUtils.ts

[CZID-9676]
Prevents object URL params being sent as `[object Object]`.
[CZID-9676]: https://czi-tech.atlassian.net/browse/CZID-9676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Always stringify object query params

---

json-schemas/sampleForReportResponse.json
tests/__snapshots__/UnifiedSchema.test.ts.snap

[CZID-9618]
added pinned_alignment_config to response so that we can kick off CG reports from mNGS page with pinned value rather than using the workflow run inputs. 
[CZID-9618]: https://czi-tech.atlassian.net/browse/CZID-9618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add pinned_alignment_config to SampleForReportResponse

---

.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/sandbox/main.tf
.happy/terraform/envs/staging/main.tf

As discovered by @jakeyheath, the app in staging takes around 80 seconds to start, so health checks start to fail before that.  Configuring `initial_delay_seconds` allows the server to start up before health checks begin.  This PR adds the config for sandbox, staging and prod.

fix: add initial_delay_seconds in terraform

---

.meshrc.yaml

`healthCheckEndpoint` is not supposed in our version of graphql mesh
including it in config actually causes a warning when running `mesh build`
```
> mesh build
🕸️  Mesh 💡 Cleaning existing artifacts
🕸️  Mesh 💡 Reading the configuration
🕸️  Mesh - config ⚠️ Configuration file is not valid!
🕸️  Mesh - config ⚠️ This is just a warning! It doesn't have any effects on runtime.
🕸️  Mesh - config ⚠️ Error: must NOT have additional properties
🕸️  Mesh 💡 Generating the unified schema
```

fix: Remove unsupported healthCheckEndpoint config
