chanzuckerberg/czid-graphql-federation-server

CHANGELOG.md
[CZID-8747]
Remove links in changelog that refer to previous repository
[CZID-8747]: https://czi-tech.atlassian.net/browse/CZID-8747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Remove broken release tag, PR, and commit links in changelog

.meshrc.yaml
[CZID-8750]
Add `workflowRunId` argument to`PipelineData` query.
Tested locally
[CZID-8750]: https://czi-tech.atlassian.net/browse/CZID-8750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: enable additional variables for PipelineData

sources/czid-schema.graphql
Reverts chanzuckerberg/czid-graphql-federation-server#16
going to re-merge this as a breaking change.
=> revert: "chore: swap sampleId type to ID to support QualityControlQuery"

.meshrc.yaml, CHANGELOG.md, json-schemas/kickoffWorkflow.json, resolvers.ts, sample-responses/kickoffWorkflow.json
[CZID-8261](https://czi-tech.atlassian.net/browse/CZID-8261)
Federated Kickoff Workflow endpoint
[CZID-8261]: https://czi-tech.atlassian.net/browse/CZID-8261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added kickoff_workflow

json-schemas/consensusGenomeWorkflowResults.json
Reverting schema to match next gen format
=> fix: Change schema back to next gen format

.meshrc.yaml, json-schemas/kickoffWorkflow.json, sample-responses/kickoffWorkflow.json
[CZID-XXXX]
This PR fixes a bug with the json-schema where it was using an object field as the top level type instead of arrays.
Fixes another issue where mesh converts a string to date.
=> fix: Updated schema for kick off workflow

resolvers.ts
[CZID-8598]
A small fix as I work through edge cases in the ConsensusGenomeWorkflowResults migration to GQL
[CZID-8598]: https://czi-tech.atlassian.net/browse/CZID-8598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ConsensusGenomeWorkflowResults - add fall back for null values

docker-compose.yml
[CZID-9162]
This makes the entities & workflows URL's available to the GQL federation service in local development. The service can use these environment variables to reach the appropriate backend. We'll populate these URL's with the appropriate values in remote-dev, staging, and prod as well, once those URL's are available
[CZID-9162]: https://czi-tech.atlassian.net/browse/CZID-9162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add URL's for entities & workflows services in local dev

.github/workflows/deploy-prod.yml
[CZID-9222]
Add logging to debug release object request
=> chore: add logging to figure out why tag name is undefined

.github/workflows/deploy-prod.yml
=> chore: add await to get api call result

.github/workflows/deploy-prod.yml
=> fix: Access tag name path correctly

.github/workflows/deploy-prod.yml
=> fix: quote release tag

.github/actions/get-release-tag/action.yml, .github/workflows/deploy-prod.yml
=> feat: move get release tag into composite action

.github/workflows/deploy-prod.yml
=> fix: Checkout repo with release tag from action

.github/workflows/deploy-prod.yml
=> fix: pass requested release tag to action

.github/actions/happy-config-set/action.yml, .github/workflows/conventional-commits.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-sandbox.yml, .github/workflows/deploy-staging.yml, .github/workflows/jest-unit-tests.yml, .happy/terraform/envs/dev/main.tf, .happy/terraform/envs/prod/main.tf, .happy/terraform/envs/sandbox/main.tf, .happy/terraform/envs/staging/main.tf
N/A
Based on recommendation from Happy Path team, pinning happy-stack-eks for system stability.  The current `main` branch had a problem that caused our server to become inaccessible.
=> fix(ci): Pin happy stack eks to working version

.happy/terraform/envs/dev/main.tf, .meshrc.yaml, Makefile, sources/entities-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
[CZID-9279](https://czi-tech.atlassian.net/browse/CZID-9279)
* Add entities as a data source 
* Does a passthrough of the authorization token
* Tested locally and on dev deploy
[CZID-9279]: https://czi-tech.atlassian.net/browse/CZID-9279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [CZID-9279] Add entities to graphql sources

.meshrc.yaml, resolvers.ts
=> chore: fix mesh warning and code formatting

resolvers.ts, utils/httpUtils.ts
Adding a util function to shared feature branch
=> [collab on feature branch] - add fetchNextGen util function

resolvers.ts
none
The frontend expected a string id, so this converts it.
=> fix: return id as a string

docker-compose.yml, package-lock.json, package.json
=> feat: Use nodemon to auto restart mesh after files change.

.meshrc.yaml, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
This is to maintain backwards compatibility for the FE while we migrate to the `fed` prefix.
New endpoint not used yet.
=> chore: Copy/paste workflowRuns into fedWorkflowRuns

.meshrc.yaml, Makefile, package-lock.json, package.json, sources/nextgen-entities-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
I know ideally we'd like to have a *copy* type of operation so we can seamlessly move this back where it needs to be long-term, but so far the transform plugs I've been working with don't quite seem to do that 😱 ... this should get us unblocked for now and buy some time to figure out the better solution.
=> chore: Temporarily rename nextgen workflowRuns top level field to tempWorkflowRuns

json-schemas/mngsWorkflowResults.json, json-schemas/taxons.json, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap, utils/mngsWorkflowResultsUtils.ts
[CZID-8737]
[CZID-8737]: https://czi-tech.atlassian.net/browse/CZID-8737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Czid 8737 switch underscores

sources/nextgen-entities-schema.graphql, sources/nextgen-workflows-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
=> chore: Update the nextgen schemas to the latest version

resolvers.ts, utils/httpUtils.ts
=> fix: type fix & http utils edits

example-queries/create-bulk-download-query.graphql, json-schemas/createBulkDownload.json, tests/CreateBulkDownload.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
Reverts chanzuckerberg/czid-graphql-federation-server#121
Reverts fix for BulkDownloadModal bug on staging : https://czi-sci.slack.com/archives/C03DNKFJT2Q/p1709074344826729?thread_ts=1708984725.669369&cid=C03DNKFJT2Q
=> fix: Revert "fix: update mutation to expect a string and tests"

resolvers.ts
Reverts chanzuckerberg/czid-graphql-federation-server#115
Reverts fix for FE query that caused a bug: https://github.com/chanzuckerberg/czid-web-private/pull/4277#pullrequestreview-1885861088
=> fix: Revert "fix: return id as a string"

.github/workflows/deploy-sandbox.yml, .github/workflows/deploy-staging.yml, .happy/terraform/envs/sandbox/main.tf
* Updates the staging environment deploy to set the env variables NEXTGEN_ENTITIES_URL and NEXTGEN_WORKFLOWS_URL
* removes the manual setting of those variables from the `tf` file for sandbox deploy
=> feat: update staging env variables urls

json-schemas/workflowRunsRequest.json, tests/__snapshots__/UnifiedSchema.test.ts.snap
This is how we're going to filter out deprecated runs.
Argument not used yet.
=> feat: Add deprecated filter to federated request

example-queries/sequencing-reads-query.graphql, resolvers.ts, tests/SequencingReadsQuery.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
The queries are synchronous because `workflowRuns` doesn't give us `railsSampleId`s.
Being flag
=> feat: Join NextGen data with Rails data in resolver

sources/nextgen-entities-schema.graphql, sources/nextgen-workflows-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
Changes since Tuesday.
Feature flagged.
=> feat: Update NextGen schema

resolvers.ts, tests/SampleForReportQuery.test.ts
no ticket
Sample Id was being sent back to sample report incorrectly causing a HOST of problems. This is the small fix. 
**With no flag**
- Sample Report MNGS tab loads
- Sample Details sidebar opens with data 
- Pipeline Tab in Details sidebar has data 
- CG tab loads
=> fix: fix malformed id

utils/httpUtils.ts
=> fix: Small Change for new version

.vscode/settings.json, tsconfig.json
none
Something in the tsconfig was causing containers to crash during deployment.
=> fix: Tsconfig to allow deployment

resolvers.ts
Since I don't know where the NextGen logs are.
=> feat: Log NextGen responses when they error

resolvers.ts
[CZID-9382](https://czi-tech.atlassian.net/browse/CZID-9382)
Query param needs quotes around it.
- Ziplink should download on Consensus Genomes
[CZID-9382]: https://czi-tech.atlassian.net/browse/CZID-9382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: make sure query param is a string

resolvers.ts
[CZID-9382](https://czi-tech.atlassian.net/browse/CZID-9382)
Small Fix: Change the service that we are querying.
Also remove excess console.logs.
- should download ziplink
[CZID-9382]: https://czi-tech.atlassian.net/browse/CZID-9382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Ziplink querying wrong service

resolvers.ts
I'm getting an error with no message and no logs in Fed or NextGen.
=> feat: Add temporary logs to fedSequencingReads

resolvers.ts, tests/WorkflowRunsQuery.test.ts, utils/httpUtils.ts, utils/queryFormatUtils.ts
none
Connect validation query to NextGen
=> feat: Connect validation query to nextgen

utils/aggregateUtils.ts
=> fix: Temporarily try seeing if fake paginating the aggregates query would solve the performance problem

utils/aggregateUtils.ts
Confirmed reducing to 20 did not have noticeable performance issues.
Project aggregates past the first page will show up again.
=> fix: Remove hack for testing

example-queries/workflows-aggregate-query.graphql, json-schemas/workflowRunsAggregateRequest.json, resolvers.ts, tests/WorkflowRunsAggregateQuery.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
The Rails call is still going to grab everything because it doesn't support this kind of pagination.
Not used yet.
=> feat: Add collectionId to where of workflowRunsAggregate so that we can paginate the query

resolvers.ts
Now that we've verified that we don't need (and can't because the URL is too long?) to pass in the `sampleIds` query param to Rails, these don't have to be synchronous.
Also get rid of all my `console.log()`s.
No behavioral change.
=> feat: Parallelize the Rails and NexGen join calls for fedSequencingReads ID query

json-schemas/sequencingReadsRequest.json, tests/__snapshots__/UnifiedSchema.test.ts.snap
`_iregex` will do ignore case and allow us to implement the existing functionality of performing "and"s on the word sequences entered (using lookarounds).
Not used yet.
=> feat: Add sample name match argument

json-schemas/consensusGenomesRequest.json, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
Reverts chanzuckerberg/czid-graphql-federation-server#220
=> chore: Revert "chore: Add sampleIds & workflowRunIds on fedConsensusGenome for API testing"

json-schemas/consensusGenomesRequest.json, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
=> feat: Add filtering by sampleIds & workflowRunIds on /worklflow_runs for API testing

sources/nextgen-entities-schema.graphql, sources/nextgen-workflows-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
Update GraphQL schema for new deleted at columns
Will be used by Rails
=> chore: Update schema for deleted at

utils/httpUtils.ts
=> feat: Also print query inputs in logs.

resolver-functions/BulkDownloadsCGOverview.ts, resolvers.ts
[CZID-9386](https://czi-tech.atlassian.net/browse/CZID-9386)
Need to merge to main so I can release and start testing on staging as I am blocked from testing on sandbox.
not working yet but shouldn't break anything with next gen flag off
n/a
[CZID-9386]: https://czi-tech.atlassian.net/browse/CZID-9386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: begin testing BulkDownloadCGOverview to nextGen

sources/nextgen-entities-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
N/A
Update the nextGen entity schema in the source file to pick up the following updates:
* Remove downloadDisplayName from bulkDownload
* Redefine downloadType for bulkDownload
See the platformics PR for more details: https://github.com/chanzuckerberg/czid-platformics/pull/265
N/A
N/A
=> chore: Update nextGen entity schema

resolver-functions/BulkDownloadsCGOverview.ts, resolvers.ts
[CZID-9386](https://czi-tech.atlassian.net/browse/CZID-9386)
Need to merge to main so I can release and start testing on staging as I am blocked from testing on sandbox.
not working yet but shouldn't break anything with next gen flag off
n/a
[CZID-9386]: https://czi-tech.atlassian.net/browse/CZID-9386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: bulk download overview in progress

json-schemas/bulkDownloads.json, resolver-functions/fedBulkDownloads.ts, tests/BulkDownloadsQuery.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
no ticket
fixes to params types for Consensus Genome Bulk Download list
web app PR is here - https://github.com/chanzuckerberg/czid-web-private/pull/4432/
=> fix: change the type of BulkDownloadCGOverview.params

CHANGELOG.md, json-schemas/bulkDownloads.json, package-lock.json, package.json, resolver-functions/BulkDownloadsCGOverview.ts, resolver-functions/fedBulkDownloads.ts, sample-responses/cgOverview.json, sources/nextgen-entities-schema.graphql, tests/BulkDownloadCGOverview.test.ts, tests/BulkDownloadsQuery.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap, utils/httpUtils.ts
[[CZID-9386]](https://czi-tech.atlassian.net/browse/CZID-9386)
Hook up include metadata checkbox
[CZID-9386]: https://czi-tech.atlassian.net/browse/CZID-9386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Adds metadata to CSV from rails

.github/workflows/deploy-sandbox.yml, .github/workflows/deploy-staging.yml
N/A
Set `DEBUG=1` in env vars, to enable more detailed logs
N/A
N/A
=> feat: Enable more detailed logs in sandbox and staging envs

utils/httpUtils.ts
none
add back query console log
=> fix: Add back query log

.meshrc.yaml, example-queries/workflow-runs-aggregate-total-count-query.graphql, json-schemas/fedWorkflowRunsAggregateTotalCountRequest.json, json-schemas/fedWorkflowRunsAggregateTotalCountResponse.json, resolvers.ts, sample-requests/fedWorkflowRunsAggregateTotalCount.json, sample-responses/fedWorkflowRunsAggregateTotalCount.json, tests/WorkflowRunsAggregateTotalCountQuery.test.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap, utils/aggregateUtils.ts
[CZID-9372]
Federate endpoint to aggregate total count for each workflow on the discovery view, i.e. "out of X"
Unit test
[CZID-9372]: https://czi-tech.atlassian.net/browse/CZID-9372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: federate querying total count of each workflow

.github/workflows/deploy-sandbox.yml, .github/workflows/deploy-staging.yml
Reverts chanzuckerberg/czid-graphql-federation-server#261
The additional logging didn't seem too helpful.
=> revert: Enable more detailed logs in sandbox and staging envs"

json-schemas/sequencingReadsRequest.json, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
Updates sequencingReads to add new inputs
=> feat: Add new input to fedSequencingReads - workflowRunIds and sampleIds

.gitignore, .happy/terraform/envs/dev/main.tf, .happy/terraform/envs/prod/main.tf, .happy/terraform/envs/sandbox/main.tf, .happy/terraform/envs/staging/main.tf
N/A
Update terraform config to increase memory for all environments
- ran this manually in prod, branched off latest deployed released tag.  
- https://github.com/chanzuckerberg/czid-graphql-federation-server/tree/20240328-bump-memory-in-prod
=> fix: increase memory in prod

json-schemas/deleteSamples.json, json-schemas/validateUsersCanDeleteObjects.json, resolvers.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
Bulk delete ID types should be strings as they can be nextgen ids.
=> fix: bulk delete id types

json-schemas/bulkDownloads.json, resolver-functions/SampleForReport.ts, resolver-functions/fedBulkDownloads/fedBulkDownloads.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap, utils/httpUtils.ts
no ticket
Fixes for Bulk Download list 
- addresses fileSize error messages
- param display format
This is the corresponding PR https://github.com/chanzuckerberg/czid-web-private/pull/4508
Bulk Download list should load and display info correctly.
=> fix: Bulk Download List fixes

resolver-functions/SampleForReport.ts
[CZID-9522]
Follow up to #314 -- add brackets to taxon/accession queries
[CZID-9522]: https://czi-tech.atlassian.net/browse/CZID-9522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix taxon/accession queries

sources/nextgen-entities-schema.graphql, tests/__snapshots__/UnifiedSchema.test.ts.snap
N/A
Update the nextGen entities schema in the source file to pick up the following updates:
* Rename `artic_v3` sequencingProtocol enum value to `artic_short_amplicons`
See the platformics PR for more details: https://github.com/chanzuckerberg/czid-platformics/pull/288
N/A
N/A
=> fix: update schema for artic_v3 wetlab protocol

json-schemas/adminSamplesResponse.json, sample-responses/adminSamples.json, tests/__snapshots__/UnifiedSchema.test.ts.snap
[CZID-9529]
Add required types to admin samples response
[CZID-9529]: https://czi-tech.atlassian.net/browse/CZID-9529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add required types to admin samples response

json-schemas/validateUsersCanDeleteObjects.json, resolver-functions/ValidateUserCanDeleteObjects/ValidateUserCanDeleteObjects.ts, tests/__snapshots__/UnifiedSchema.test.ts.snap
Keep `validIds` backwards-compatible.
=> fix: Change validIds field back to number, add new validIdsStrings field

.happy/terraform/envs/staging/main.tf
* unsure whether this will work, just a test for now
=> fix: bump timeout seconds

.happy/terraform/envs/staging/main.tf
=> fix: bump liveness readiness timeouts

pull_request_template.md
=> feat: Dummy PR to trigger release please

.github/workflows/deploy-prod.yml, .github/workflows/deploy-sandbox.yml, .github/workflows/deploy-staging.yml, .github/workflows/jest-unit-tests.yml, .github/workflows/reusable-deploy.yml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
=> fix: Update runs-on labels in GitHub Actions workflows
